CREATE TABLE "snapshot" (
    "id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "user_id" BIGINT REFERENCES "user" ON DELETE SET NULL,
    "operation" SMALLINT NOT NULL,
    "resource_type" SMALLINT NOT NULL,
    "resource_id" TEXT NOT NULL,
    "data" JSONB NOT NULL,
    "creation_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);