CREATE EXTENSION citext;

CREATE TABLE "user" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "name" CITEXT NOT NULL UNIQUE,
    "password_hash" VARCHAR(128) NOT NULL,
    "password_salt" VARCHAR(32) NOT NULL,
    "email" CITEXT,
    "rank" SMALLINT NOT NULL,
    "avatar_style" SMALLINT NOT NULL,
    "creation_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_login_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_edit_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
SELECT diesel_manage_last_edit_time('user');

CREATE TABLE "user_token" (
    "user_id" INTEGER PRIMARY KEY REFERENCES "user" ON DELETE CASCADE,
    "token" UUID NOT NULL UNIQUE,
    "note" VARCHAR(128) NOT NULL DEFAULT '',
    "enabled" BOOLEAN NOT NULL,
    "expiration_time" TIMESTAMP WITH TIME ZONE,
    "creation_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_edit_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_usage_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
SELECT diesel_manage_last_edit_time('user_token');