CREATE TABLE "comment" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "user_id" INTEGER NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "post_id" INTEGER NOT NULL REFERENCES "post" ON DELETE CASCADE,
    "text" TEXT NOT NULL DEFAULT '',
    "creation_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_edit_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
SELECT diesel_manage_last_edit_time('comment');

CREATE TABLE "comment_score" (
    "comment_id" INTEGER NOT NULL REFERENCES "comment" ON DELETE CASCADE,
    "user_id" INTEGER NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "score" SMALLINT NOT NULL,
    "time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("comment_id", "user_id")
);