# Http request tests

### Getting info
GET http://localhost:8080/api/info
content-Type: application/json
accept: application/json

### Listing posts no filters all fields
GET http://localhost:8080/api/posts/?query=&limit=42
content-Type: application/json
accept: application/json

### Listing posts no filters
GET http://localhost:8080/api/posts/?query=&limit=42&fields=id%2CthumbnailUrl%2Ctype%2Csafety%2Cscore%2CfavoriteCount%2CcommentCount%2Ctags%2Cversion
content-Type: application/json
accept: application/json

### Listing posts filter out unsafe
GET http://localhost:8080/api/posts/?query=-rating%3Aunsafe&limit=42&fields=id%2CthumbnailUrl%2Ctype%2Csafety%2Cscore%2CfavoriteCount%2CcommentCount%2Ctags%2Cversion
content-Type: application/json
accept: application/json

### Listing posts filter out unsafe with large offset
GET http://localhost:8080/api/posts/?query=-rating%3Aunsafe&offset=33726&limit=42&fields=id%2CthumbnailUrl%2Ctype%2Csafety%2Cscore%2CfavoriteCount%2CcommentCount%2Ctags%2Cversion
content-Type: application/json
accept: application/json

### Listing posts with tag "tagme"
GET http://localhost:8080/api/posts/?query=tagme&limit=42&fields=id%2CthumbnailUrl%2Ctype%2Csafety%2Cscore%2CfavoriteCount%2CcommentCount%2Ctags%2Cversion
content-Type: application/json
accept: application/json

### Listing posts sorted by tag count
GET http://localhost:8080/api/posts/?query=sort%3Atag-count&limit=42&fields=id%2CthumbnailUrl%2Ctype%2Csafety%2Cscore%2CfavoriteCount%2CcommentCount%2Ctags%2Cversion
content-Type: application/json
accept: application/json

### Listing tags
GET http://localhost:8080/api/tags/?limit=50&fields=names%2Csuggestions%2Cimplications%2CcreationTime%2Cusages%2Ccategory
content-Type: application/json
accept: application/json

### Listing tags sorted by usage count
GET http://localhost:8080/api/tags/?query=sort%3Ausages&limit=50&fields=names%2Csuggestions%2Cimplications%2CcreationTime%2Cusages%2Ccategory
content-Type: application/json
accept: application/json

### Tag autocomplete
GET http://localhost:8080/api/tags/?query=e*%20sort%3Ausages&limit=15&fields=names%2Ccategory%2Cusages
content-Type: application/json
accept: application/json

### Getting tag siblings
GET http://localhost:8080/api/tag-siblings/tagme/?limit=50&fields=names%2Csuggestions%2Cimplications%2CcreationTime%2Cusages%2Ccategory
content-Type: application/json
accept: application/json

### Getting post neighbors
GET http://localhost:8080/api/post/2/around/?query=&fields=id%2CthumbnailUrl%2Ctype%2Csafety%2Cscore%2CfavoriteCount%2CcommentCount%2Ctags%2Cversion
content-Type: application/json
accept: application/json

### List Users
GET http://localhost:8080/api/users/?limit=30
content-Type: application/json
accept: application/json