DROP TABLE "user_token";

CREATE TABLE "user_token" (
    "id" UUID PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user" ON DELETE CASCADE,
    "note" VARCHAR(128) NOT NULL DEFAULT '',
    "enabled" BOOLEAN NOT NULL,
    "expiration_time" TIMESTAMP WITH TIME ZONE,
    "creation_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_edit_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_usage_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);