name: Server CI

on:
  push:
    branches: [ master ]
    #paths:
    #  - 'server/**'
  pull_request:
    branches: [ master ]
    #paths:
    #  - 'server/**'

defaults:
  run:
    working-directory: server

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install-dependencies
      run: sudo apt update && sudo apt install clang pkg-config libssl-dev libpq-dev libdav1d-dev libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    
    - name: Cache Clippy
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: cargo-check
    
    - name: Run Clippy
      run: cargo clippy --all-features --all-targets -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: Run rustfmt
      run: cargo fmt -- --check

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PGUSERNAME: postgres
      PGPASSWORD: postgres
      PGDATABASE: oxi
    steps:
      - name: Install-dependencies
        run: sudo apt update && sudo apt install clang pkg-config libssl-dev libpq-dev libdav1d-dev libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev

      - name: Add PostgreSQL binaries to PATH
        shell: bash
        run: echo "$(pg_config --bindir)" >> $GITHUB_PATH

      - name: Start preinstalled PostgreSQL
        shell: bash
        run: |
          echo "Initializing database cluster..."

          export PGDATA="$PGHOST/pgdata"
          mkdir -p "$PGDATA"

          # initdb requires file for password in non-interactive mode
          export PWFILE="$RUNNER_TEMP/pwfile"
          echo "postgres" > "$PWFILE"
          initdb --pgdata="$PGDATA" --username="postgres" --pwfile="$PWFILE"

          echo "Starting PostgreSQL..."
          echo "unix_socket_directories = '$PGHOST'" >> "$PGDATA/postgresql.conf"
          pg_ctl start

          echo "Creating user..."
          psql --host "$PGHOST" --username="postgres" --dbname="postgres" --command="CREATE USER $PGUSERNAME PASSWORD '$PGPASSWORD'" --command="\du"

          echo "Creating database..."
          createdb --owner="$PGUSERNAME" --username="postgres" "$PGDATABASE"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: cp ../doc/example.env ../.env

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: cargo-check

      - name: Run tests
        run: cargo test